apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Ziyed1/K8s-Manifests.git'
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncWindow: 'daily'  # Optionnellement, tu peux utiliser un "syncWindow" si tu veux des heures spécifiques
      retry:
        limit: 3   # Nombre maximal de tentatives en cas d'échec
    syncOptions:
      - Validate=false
