apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret 
      containers:
      - name: frontend
        image: docker.io/ziyed1/crypto_webapp:frontend-65d0b4a
        ports:
        - containerPort: 80
        
