apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-webapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/ton-user/my-app-k8s-manifests.git'
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
